// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxAJq6AKhxLEeIfPK2V-Oubuew45jTYoY',
    appId: '1:27046103240:web:c5518f33216cd04678fdfd',
    messagingSenderId: '27046103240',
    projectId: 'coursenavig',
    authDomain: 'coursenavig.firebaseapp.com',
    storageBucket: 'coursenavig.appspot.com',
    measurementId: 'G-WZMRV9KV0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALmVv3yHuhnFqC0AsduMLXO_3dZu-WG28',
    appId: '1:27046103240:android:b50d0105487ed85e78fdfd',
    messagingSenderId: '27046103240',
    projectId: 'coursenavig',
    storageBucket: 'coursenavig.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtDX6e96idwV_NUCwb3J6CVFbTpgAYAWo',
    appId: '1:27046103240:ios:dff0ec772fba6a9b78fdfd',
    messagingSenderId: '27046103240',
    projectId: 'coursenavig',
    storageBucket: 'coursenavig.appspot.com',
    iosBundleId: 'com.example.courseNavigator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtDX6e96idwV_NUCwb3J6CVFbTpgAYAWo',
    appId: '1:27046103240:ios:dff0ec772fba6a9b78fdfd',
    messagingSenderId: '27046103240',
    projectId: 'coursenavig',
    storageBucket: 'coursenavig.appspot.com',
    iosBundleId: 'com.example.courseNavigator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxAJq6AKhxLEeIfPK2V-Oubuew45jTYoY',
    appId: '1:27046103240:web:ac4b6e1e83197c8778fdfd',
    messagingSenderId: '27046103240',
    projectId: 'coursenavig',
    authDomain: 'coursenavig.firebaseapp.com',
    storageBucket: 'coursenavig.appspot.com',
    measurementId: 'G-781V31VHLP',
  );
}
